name: Run CI checks

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run nx affected --target=test --base=origin/master --parallel --maxParallel=8
  lint:
    runs-on: ubuntu-latest
    name: Lint affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run nx affected --target=lint --base=origin/master --parallel --maxParallel=8
  e2e:
    runs-on: ubuntu-latest
    name: Run E2E tests on affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run nx affected --target=e2e --base=origin/master --parallel --maxParallel=8
  build:
    runs-on: ubuntu-latest
    name: Run `build` on affected apps
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
      - run: npm run nx affected --target=build --base=origin/master --parallel --maxParallel=8
